<?php

namespace app\models;

use Yii;
use yii\behaviors\TimestampBehavior;
use yii\db\Expression;

/**
 * This is the model class for table "count".
 *
 * @property int $id
 * @property int|null $user_id
 * @property int|null $cat_id
 * @property string|null $created_at
 */
class Count extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'count';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [

            [['user_id', 'cat_id'], 'integer'],
            [['created_at'],'safe'],

        ];
    }

    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            [
                'class'=> TimestampBehavior::className(),
                'createdAtAttribute' => 'created_at',
                'updatedAtAttribute' => 'updated_at',
                'value' => new Expression('Now()')
            ]
        ];
    }
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'user_id' => 'User ID',
            'cat_id' => 'Cat ID',
            'created_at' => 'Created At',
        ];
    }
//    public function beforeSave($id)
//    {
//        if($this->image_path==null){
//            $this->image_path = $this->img_file['base_url']."/".$this->img_file['path'];
//
//            //parent::beforeSave('image_path', $this->image_path); // TODO: Change the autogenerated stub
//
//        }
//        return parent::beforeSave($id);
//    }
}

